import React, { useState } from "react";
import { Navbar } from "../components/Navbar";
import ContactSection from "../components/ContactSection";

export const Declare=()=> {
  const [selectedReg, setSelectedReg] = useState(null);

  // ALL STATIC CONTENT IN ONE PLACE
  const content = {
    "Regulation 4 (4) (a)": {
      title: "Pursuant to Regulation 4 (4) (a)",
      tableHead: ["S.No", "State / Union Territory", "District"],
      tableRows: [
        ["1", "Tamil Nadu", "All the Districts"],
        ["2", "Pondicherry", "Pondicherry, Karaikal"],
        ["3", "Andhra Pradesh", "Chitoor, Nellore"],
        ["4", "Karnataka", "All the Districts"],
      ],
    },

    "Regulation 4 (4) (b)": {
      title: "Pursuant to Regulation 4 (4) (b) — Total Channel Carrying Capacity",
      tableHead: [
        "Distribution Network Location",
        "Standard Definition Channels",
        "High Definition Channels",
        "Total",
      ],
      tableRows: [
        ["Tamil Nadu", "392", "176", "568"],
        ["Pondicherry", "392", "176", "568"],
        ["Andhra Pradesh", "392", "176", "568"],
        ["Karnataka", "408", "164", "572"],
      ],
    },
"Regulation 4 (4) (c)": {
      title: "Pursuant to Regulation 4 (4) (c) — List of Channels",
      tables: [
        {
          tableHead: ["S.No", "Channel Name", "Count in SD Terms", "SD / HD"],
          tableRows: [
["1", "& FLIX", "1", "SD"],
    ["2", "& PICTURES", "1", "SD"],
    ["3", "& TV", "1", "SD"],
    ["4", "1SPORTS", "1", "SD"],
    ["5", "24 NEWS", "1", "SD"],
    ["6", "316 TV", "1", "SD"],
    ["7", "7 STAR TV", "1", "SD"],
    ["8", "7S MUSIC", "1", "SD"],
    ["9", "9X JALWA", "1", "SD"],
    ["10", "9X JHAKAAS", "1", "SD"],
    ["11", "9XM", "1", "SD"],
    ["12", "AAJ TAK", "1", "SD"],
    ["13", "AASTHA", "1", "SD"],
    ["14", "AASTHA BHAJAN", "1", "SD"],
    ["15", "ABN ANDHRA JHOTI", "1", "SD"],
    ["16", "ABP NEWS", "1", "SD"],
    ["17", "ADITHYA", "1", "SD"],
    ["18", "ADTHISYAM TV", "1", "SD"],
    ["19", "AMRITA", "1", "SD"],
    ["20", "ANANDAM TV", "1", "SD"],
    ["21", "ANGEL TV", "1", "SD"],
    ["22", "ANIMAL PLANET", "1", "SD"],
    ["23", "ANNAI TV", "1", "SD"],
    ["24", "ARADANA", "1", "SD"],
    ["25", "ARIHANT", "1", "SD"],
    ["26", "ARK TV", "1", "SD"],
    ["27", "ARPUTHAR YESU", "1", "SD"],
    ["28", "ARULJOTHI", "1", "SD"],
    ["29", "ASEERVATHAM", "1", "SD"],
    ["30", "ASIANET", "1", "SD"],
    ["31", "ASIANET MOVIES", "1", "SD"],
    ["32", "ASIANET NEWS", "1", "SD"],
    ["33", "ASIANET PLUS", "1", "SD"],
    ["34", "ASIANET SUVARNA NEWS", "1", "SD"],
    ["35", "AYYA VAIKUNDAT VAZHI TV", "1", "SD"],
    ["36", "B4U MOVIES", "1", "SD"],
    ["37", "B4U MUSIC", "1", "SD"],
    ["38", "BB TV", "1", "SD"],
    ["39", "BBC CBEEBIES", "1", "SD"],
    ["40", "BBC WORLD NEWS", "1", "SD"],
    ["41", "BHAKTHI", "1", "SD"],
    ["42", "BIG MAGIC", "1", "SD"],
    ["43", "CAPTAIN NEWS", "1", "SD"],
    ["44", "CAPTAIN TV", "1", "SD"],
    ["45", "CARE WORLD", "1", "SD"],
    ["46", "CARTOON NETWORK", "1", "SD"],
    ["47", "CHANNEL WIN", "1", "SD"],
    ["48", "CHINTU TV", "1", "SD"],
    ["49", "CHITHIRAM", "1", "SD"],
    ["50", "CHUTTI TV", "1", "SD"],
    ["51", "CINEMA TV", "1", "SD"],
    ["52", "CNBC AWAAZ", "1", "SD"],
    ["53", "CNBC TV18", "1", "SD"],
    ["54", "CNN INTERNATIONAL", "1", "SD"],
    ["55", "CNN NEWS18", "1", "SD"],
    ["56", "COLORS", "1", "SD"],
    ["57", "COLORS BANGLA", "1", "SD"],
    ["58", "COLORS CINEPLEX", "1", "SD"],
    ["59", "COLORS GUJRATHI", "1", "SD"],
    ["60", "COLORS INFINITY", "1", "SD"],
    ["61", "COLORS KANNADA", "1", "SD"],
    ["62", "COLORS KANNADA CINEMA", "1", "SD"],
    ["63", "COLORS MARATHI", "1", "SD"],
    ["64", "COLORS ODIA", "1", "SD"],
    ["65", "COLORS RISHTEY", "1", "SD"],
    ["66", "COLORS SUPER", "1", "SD"],
    ["67", "COLORS TAMIL", "1", "SD"],
    ["68", "COMEDY CENTRAL", "1", "SD"],
    ["69", "CONSUMER INFO", "1", "SD"],
    ["70", "CROSS TV", "1", "SD"],
    ["71", "CVR HEALTH", "1", "SD"],
    ["72", "D JEYAM", "1", "SD"],
    ["73", "D TAMIL", "1", "SD"],
    ["74", "DARSHANA TV", "1", "SD"],
    ["75", "DD ARUNPRABHA", "1", "SD"],
    ["76", "DD BANGLA", "1", "SD"],
    ["77", "DD BHARATHI", "1", "SD"],
    ["78", "DD BIHAR", "1", "SD"],
    ["79", "DD CHANDANA", "1", "SD"],
    ["80", "DD GIRNAR", "1", "SD"],
    ["81", "DD GYANDHARASHAN 1", "1", "SD"],
    ["82", "DD GYANDHARASHAN 2", "1", "SD"],
    ["83", "DD INDIA", "1", "SD"],
    ["84", "DD KASHIR", "1", "SD"],
    ["85", "DD KISAN", "1", "SD"],
    ["86", "DD KISHORE MANCH", "1", "SD"],
    ["87", "DD MALAYALAM", "1", "SD"],
    ["88", "DD MP", "1", "SD"],
    ["89", "DD NATIONAL", "1", "SD"],
    ["90", "DD NEWS", "1", "SD"],
    ["91", "DD NORTHEAST", "1", "SD"],
    ["92", "DD ODIA", "1", "SD"],
    ["93", "DD PANINI", "1", "SD"],
    ["94", "DD PODHIGAI", "1", "SD"],
    ["95", "DD PUDUCHERRY", "1", "SD"],
    ["96", "DD PUNJABI", "1", "SD"],
    ["97", "DD RAJASTHAN", "1", "SD"],
    ["98", "DD SAHYADRI", "1", "SD"],
    ["99", "DD SANSAD TV LOKSHABHA", "1", "SD"],
    ["100", "DD SANSAD TV RAJYASABHA", "1", "SD"],
      ["101", "DD SAPTHAGIRI", "1", "SD"],
    ["102", "DD SHARDA", "1", "SD"],
    ["103", "DD SPORTS", "1", "SD"],
    ["104", "DD UP", "1", "SD"],
    ["105", "DD URDU", "1", "SD"],
    ["106", "DD YADAGIRI", "1", "SD"],
    ["107", "DHEERAN TV", "1", "SD"],
    ["108", "DISCOVERY", "1", "SD"],
    ["109", "DISCOVERY KIDS", "1", "SD"],
    ["110", "DISCOVERY SCIENCE", "1", "SD"],
    ["111", "DISCOVERY TURBO", "1", "SD"],
    ["112", "DISNEY", "1", "SD"],
    ["113", "DISNEY JUNIOR", "1", "SD"],
    ["114", "DIVYA", "1", "SD"],
    ["115", "DW ASIA", "1", "SD"],
    ["116", "DY 365", "1", "SD"],
    ["117", "El SHADDAI", "1", "SD"],
    ["118", "ENTER 10", "1", "SD"],
    ["119", "EPIC TV", "1", "SD"],
    ["120", "ET NOW", "1", "SD"],
    ["121", "ET NOW SWADESH", "1", "SD"],
    ["122", "ETV", "1", "SD"],
    ["123", "ETV ABIRUCHI", "1", "SD"],
    ["124", "ETV AP", "1", "SD"],
    ["125", "ETV BAL BHARAT SD", "1", "SD"],
    ["126", "ETV CINEMA", "1", "SD"],
    ["127", "ETV LIFE", "1", "SD"],
    ["128", "ETV PLUS", "1", "SD"],
    ["129", "ETV TELANGANA", "1", "SD"],
    ["130", "EUROSPORT", "1", "SD"],
    ["131", "FAMILY TV", "1", "SD"],
    ["132", "FASHION TV", "1", "SD"],
    ["133", "FILAMCHI", "1", "SD"],
    ["134", "FILMY", "1", "SD"],
    ["135", "FLOWERS TV", "1", "SD"],
    ["136", "FOOD FOOD", "1", "SD"],
    ["137", "FOX LIFE", "1", "SD"],
    ["138", "FRANCE TV", "1", "SD"],
    ["139", "GEMINI COMEDY", "1", "SD"],
    ["140", "GEMINI LIFE", "1", "SD"],
    ["141", "GEMINI MOVIES", "1", "SD"],
    ["142", "GEMINI MUSIC", "1", "SD"],
    ["143", "GEMINI TV", "1", "SD"],
    ["144", "GNT", "1", "SD"],
    ["145", "GOODNESS", "1", "SD"],
    ["146", "GUBBARE", "1", "SD"],
    ["147", "HEAVEN TV", "1", "SD"],
    ["148", "HISTORY TV18", "1", "SD"],
    ["149", "HOPE 24X7", "1", "SD"],
    ["150", "HUNGAMA", "1", "SD"],
    ["151", "IMAYAM TV", "1", "SD"],
    ["152", "INDIA TODAY", "1", "SD"],
    ["153", "INVESTIGATION DISCOVERY", "1", "SD"],
    ["154", "ISAI ARUVI", "1", "SD"],
    ["155", "ISHARA", "1", "SD"],
    ["156", "J MOVIES", "1", "SD"],
    ["157", "J TV", "1", "SD"],
    ["158", "JANAM TV", "1", "SD"],
    ["159", "JAY TV", "1", "SD"],
    ["160", "JAYA MAX", "1", "SD"],
    ["161", "JAYA PLUS", "1", "SD"],
    ["162", "JAYA TV", "1", "SD"],
    ["163", "JEEVAN TV", "1", "SD"],
    ["164", "JEEVAOLI TV", "1", "SD"],
    ["165", "JEYAM PLUS", "1", "SD"],
    ["166", "JEYAM TV", "1", "SD"],
    ["167", "JOHTI TV", "1", "SD"],
    ["168", "JOY TV", "1", "SD"],
    ["169", "KAIRALI", "1", "SD"],
    ["170", "KAIRALI NEWS", "1", "SD"],
    ["171", "KAIRALI WE", "1", "SD"],
    ["172", "KALAIGNAR TV", "1", "SD"],
    ["173", "KALVI CHOLAI", "1", "SD"],
    ["174", "KALVI TV", "1", "SD"],
    ["175", "KAPPA TV", "1", "SD"],
    ["176", "KARAN TV", "1", "SD"],
    ["177", "KASTHURI NEWS", "1", "SD"],
    ["178", "KASTHURI TV", "1", "SD"],
    ["179", "KERALA VISION", "1", "SD"],
    ["180", "KOCHU TV", "1", "SD"],
    ["181", "KTV", "1", "SD"],
    ["182", "KUSHI TV", "1", "SD"],
    ["183", "MADHA TV", "1", "SD"],
    ["184", "MADHIMUGAM", "1", "SD"],
    ["185", "MAKKAL TV", "1", "SD"],
    ["186", "MALAI MURASU", "1", "SD"],
    ["187", "MANORAMA NEWS", "1", "SD"],
    ["188", "MANORANJAN TV", "1", "SD"],
    ["189", "MARKET ZONE", "1", "SD"],
    ["190", "MARVEL HQ", "1", "SD"],
    ["191", "MASTII", "1", "SD"],
    ["192", "MATHRUBHUMI NEWS", "1", "SD"],
    ["193", "MAZHAVIL MANORAMA", "1", "SD"],
    ["194", "MEGA 24", "1", "SD"],
    ["195", "MEGA MUSIC", "1", "SD"],
    ["196", "MEGA TV", "1", "SD"],
    ["197", "MIRROR NOW", "1", "SD"],
    ["198", "MNX", "1", "SD"],
    ["199", "MOVIES NOW", "1", "SD"],
    ["200", "MTV", "1", "SD"],
    ["201", "MTV BEATS", "1", "SD"],
    ["202", "MUSIC INDIA", "1", "SD"],
  ["203", "MUSIC ZONE", "1", "SD"],
  ["204", "N TV", "1", "SD"],
  ["205", "NAAPTOL TAMIL", "1", "SD"],
  ["206", "NAMBIKAI TV", "1", "SD"],
  ["207", "NAT GEO WILD", "1", "SD"],
  ["208", "NDTV 24X7", "1", "SD"],
  ["209", "NDTV GOODTIMES", "1", "SD"],
  ["210", "NDTV INDIA", "1", "SD"],
  ["211", "NDTV PROFIT", "1", "SD"],
  ["212", "NEPAL 1", "1", "SD"],
  ["213", "NEWS J", "1", "SD"],
  ["214", "NEWS18 INDIA", "1", "SD"],
  ["215", "NEWS18 KANNADA", "1", "SD"],
  ["216", "NEWS18 LOKMAT", "1", "SD"],
  ["217", "NEWS18 RAJASTHAN", "1", "SD"],
  ["218", "NEWS18 TAMILNADU", "1", "SD"],
  ["219", "NEWS18 URDU", "1", "SD"],
  ["220", "NEWS7 TAMIL", "1", "SD"],
  ["221", "NEWSTAMIL24X7", "1", "SD"],
  ["222", "NGC", "1", "SD"],
  ["223", "NICK", "1", "SD"],
  ["224", "NICK JUNIOR", "1", "SD"],
  ["225", "NIJAM TV", "1", "SD"],
  ["226", "NIKKI TV", "1", "SD"],
  ["227", "NITHIYAM", "1", "SD"],
  ["228", "OM TV", "1", "SD"],
  ["229", "OSHO TV", "1", "SD"],
  ["230", "PARAS TV", "1", "SD"],
  ["231", "PC TV", "1", "SD"],
  ["232", "PEACE OF MIND", "1", "SD"],
  ["233", "POGO", "1", "SD"],
  ["234", "POLIMER", "1", "SD"],
  ["235", "POLIMER NEWS", "1", "SD"],
  ["236", "PTC PUNJABI", "1", "SD"],
  ["237", "PUBLIC MUSIC", "1", "SD"],
  ["238", "PUTHIYA THALAIMURAI", "1", "SD"],
  ["239", "PUTHUYUGAM", "1", "SD"],
  ["240", "REPORTER", "1", "SD"],
  ["241", "REPUBLIC TV", "1", "SD"],
  ["242", "RISTHEY CINEPLEX", "1", "SD"],
  ["243", "ROMEDY NOW", "1", "SD"],
  ["244", "RUAH TV", "1", "SD"],
  ["245", "RUSSIA TODAY", "1", "SD"],
  ["246", "SAFARI", "1", "SD"],
  ["247", "SAHARA ONE", "1", "SD"],
  ["248", "SAI TV", "1", "SD"],
  ["249", "SAKSHI TV", "1", "SD"],
  ["250", "SANGAMAM", "1", "SD"],
  ["251", "SANSKAR", "1", "SD"],
  ["252", "SARVESH TV", "1", "SD"],
  ["253", "SATHIYAM", "1", "SD"],
  ["254", "SCN CHANNEL", "1", "SD"],
  ["255", "SEITHIGAL", "1", "SD"],
  ["256", "SHALOM", "1", "SD"],
  ["257", "SHOPPING INFO", "1", "SD"],
  ["258", "SHREE TV", "1", "SD"],
  ["259", "SIRIPOLI", "1", "SD"],
  ["260", "SKY TV", "1", "SD"],
  ["261", "SMART TV", "1", "SD"],
  ["262", "SMYRNA TV", "1", "SD"],
  ["263", "SONIC", "1", "SD"],
  ["264", "SONY AATH", "1", "SD"],
  ["265", "SONY BBC EARTH", "1", "SD"],
  ["266", "SONY ENTERTAINMENT", "1", "SD"],
  ["267", "SONY MARATHI", "1", "SD"],
  ["268", "SONY MAX", "1", "SD"],
  ["269", "SONY MAX 2", "1", "SD"],
  ["270", "SONY PAL", "1", "SD"],
  ["271", "SONY PIX", "1", "SD"],
  ["272", "SONY SAB", "1", "SD"],
  ["273", "SONY SIX", "1", "SD"],
  ["274", "SONY TEN 1", "1", "SD"],
  ["275", "SONY TEN 2", "1", "SD"],
  ["276", "SONY TEN 3", "1", "SD"],
  ["277", "SONY TEN 4", "1", "SD"],
  ["278", "SONY WAH", "1", "SD"],
  ["279", "SONY YAY", "1", "SD"],
  ["280", "SR TV", "1", "SD"],
  ["281", "SRI SANKARA", "1", "SD"],
  ["282", "STAR BHARAT", "1", "SD"],
  ["283", "STAR GOLD", "1", "SD"],
  ["284", "STAR GOLD 2", "1", "SD"],
  ["285", "STAR GOLD SELECT", "1", "SD"],
  ["286", "STAR JALSHA", "1", "SD"],
  ["287", "STAR JALSHA MOVIES", "1", "SD"],
  ["288", "STAR MAA GOLD", "1", "SD"],
  ["289", "STAR MAA MOVIES", "1", "SD"],
  ["290", "STAR MAA MUSIC", "1", "SD"],
  ["291", "STAR MAA TV", "1", "SD"],
  ["292", "STAR MOVIES", "1", "SD"],
  ["293", "STAR PARVAH", "1", "SD"],
  ["294", "STAR PLUS", "1", "SD"],
  ["295", "STAR SPORTS 1", "1", "SD"],
  ["296", "STAR SPORTS 1 HINDI", "1", "SD"],
  ["297", "STAR SPORTS 1 KANNADA", "1", "SD"],
  ["298", "STAR SPORTS 1 TAMIL", "1", "SD"],
  ["299", "STAR SPORTS 1 TELUGU", "1", "SD"],
  ["300", "STAR SPORTS 2", "1", "SD"],
  ["301", "STAR SPORTS 3", "1", "SD"],
  ["302", "STAR SPORTS FIRST", "1", "SD"],
  ["303", "STAR SPORTS SELECT 1", "1", "SD"],
  ["304", "STAR SPORTS SELECT 2", "1", "SD"],
  ["305", "STAR SUVARNA", "1", "SD"],
  ["306", "STAR SUVARNA PLUS", "1", "SD"],
  ["307", "STAR UTSAV", "1", "SD"],
  ["308", "STAR UTSAV MOVIES", "1", "SD"],
  ["309", "STAR VIJAY", "1", "SD"],
  ["310", "STAR VIJAY MUSIC", "1", "SD"],
  ["311", "STAR VIJAY SUPER", "1", "SD"],
  ["312", "STAR WORLD", "1", "SD"],
  ["313", "SUBHAVAARTHA", "1", "SD"],
  ["314", "SUN BANGLA", "1", "SD"],
  ["315", "SUN LIFE", "1", "SD"],
  ["316", "SUN MUSIC", "1", "SD"],
  ["317", "SUN NEWS", "1", "SD"],
  ["318", "SUN TV", "1", "SD"],
  ["319", "SURYA", "1", "SD"],
  ["320", "SURYA COMEDY", "1", "SD"],
  ["321", "SURYA MOVIES", "1", "SD"],
  ["322", "SURYA MUSIC", "1", "SD"],
  ["323", "SVBC TAMIL", "1", "SD"],
  ["324", "SVBC TELUGU", "1", "SD"],
  ["325", "TAMILAN TV", "1", "SD"],
  ["326", "TCCL INFO", "1", "SD"],
  ["327", "TEHZEEB", "1", "SD"],
  ["328", "TELE SHOPPING", "1", "SD"],
  ["329", "TEST SD", "1", "SD"],
  ["330", "THANTHI TV", "1", "SD"],
  ["331", "TIMES NOW", "1", "SD"],
  ["332", "TIMESNOW NAVBHARAT SD", "1", "SD"],
  ["333", "TLC", "1", "SD"],
  ["334", "TRAVEL XP", "1", "SD"],
  ["335", "TRAVEL XP TAMIL", "1", "SD"],
  ["336", "TV5 MONDE", "1", "SD"],
  ["337", "TV5 NEWS", "1", "SD"],
  ["338", "TV9 KANNADA", "1", "SD"],
  ["339", "TV9 TELUGU", "1", "SD"],
  ["340", "UDAYA COMEDY", "1", "SD"],
  ["341", "UDAYA MOVIES", "1", "SD"],
  ["342", "UDAYA MUSIC", "1", "SD"],
  ["343", "UDAYA TV", "1", "SD"],
  ["344", "UTV ACTION", "1", "SD"],
  ["345", "UTV BINDASS", "1", "SD"],
  ["346", "UTV MOVIES", "1", "SD"],
  ["347", "V TV", "1", "SD"],
  ["348", "VAIGAI TV", "1", "SD"],
  ["349", "VANAVIL PLUS", "1", "SD"],
  ["350", "VANITHA TV", "1", "SD"],
  ["351", "VASANTH TV", "1", "SD"],
  ["352", "VELICHAM TV", "1", "SD"],
  ["353", "VENDHAR TV", "1", "SD"],
  ["354", "VH1", "1", "SD"],
  ["355", "VINMEEN MUSIC", "1", "SD"],
  ["356", "WIN TV", "1", "SD"],
  ["357", "WION TV", "1", "SD"],
  ["358", "WOW CINEMA", "1", "SD"],
  ["359", "ZEE 24 GHANTA", "1", "SD"],
  ["360", "ZEE 24 TAAS", "1", "SD"],
  ["361", "ZEE ACTION", "1", "SD"],
  ["362", "ZEE ANMOL", "1", "SD"],
  ["363", "ZEE BANGLA", "1", "SD"],
  ["364", "ZEE BANGLA CINEMA", "1", "SD"],
  ["365", "ZEE BOLLYWOOD", "1", "SD"],
  ["366", "ZEE BUSINESS", "1", "SD"],
  ["367", "ZEE CAFE", "1", "SD"],
  ["368", "ZEE CINEMA", "1", "SD"],
  ["369", "ZEE CINEMALU", "1", "SD"],
  ["370", "ZEE CLASSIC", "1", "SD"],
  ["371", "ZEE HINDUSTAN", "1", "SD"],
  ["372", "ZEE KALINGA", "1", "SD"],
  ["373", "ZEE KANNADA", "1", "SD"],
  ["374", "ZEE KERALAM", "1", "SD"],
  ["375", "ZEE MARATHI", "1", "SD"],
  ["376", "ZEE NEWS", "1", "SD"],
  ["377", "ZEE PICCHAR", "1", "SD"],
  ["378", "ZEE PUNJABI HARYANA", "1", "SD"],
  ["379", "ZEE SALAM", "1", "SD"],
  ["380", "ZEE TALKIES", "1", "SD"],
  ["381", "ZEE TAMIL", "1", "SD"],
  ["382", "ZEE TELUGU", "1", "SD"],
  ["383", "ZEE THIRAI", "1", "SD"],
  ["384", "ZEE TV", "1", "SD"],
  ["385", "ZEE YUVA", "1", "SD"],
  ["386", "ZEE ZEST", "1", "SD"],
  ["387", "ZING", "1", "SD"],
  ["388", "ZOOM", "1", "SD"],
  ["389", "", "1", "SD"],
    ["390", "& FLIX HD", "2", "HD"],
    ["391", "& PICTURES HD", "2", "HD"],
    ["392", "& PRIVE HD", "2", "HD"],
    ["393", "AAJ TAK HD", "2", "HD"],
    ["394", "ANIMAL PLANET HD", "2", "HD"],
    ["395", "ASIANET HD", "2", "HD"],
    ["396", "BABY TV HD", "2", "HD"],
    ["397", "CN HD+", "2", "HD"],
    ["398", "CNBC PRIME HD", "2", "HD"],
    ["399", "COLORS CINEPLEX HD", "2", "HD"],
    ["400", "COLORS HD", "2", "HD"],
    ["401", "COLORS INFINITY HD", "2", "HD"],
    ["402", "COLORS KANNADA HD", "2", "HD"],
    ["403", "COLORS TAMIL HD", "2", "HD"],
    ["404", "COMEDY CENTRAL HD", "2", "HD"],
    ["405", "DD NATIONAL HD", "2", "HD"],
    ["406", "DISCOVERY HD WORLD", "2", "HD"],
    ["407", "DISNEY INTR HD", "2", "HD"],
    ["408", "ETV BAL BHARAT HD", "2", "HD"],
    ["409", "ETV HD", "2", "HD"],
    ["410", "EUROSPORT HD", "2", "HD"],
    ["411", "FASHION TV HD", "2", "HD"],
    ["412", "FOX LIFE HD", "2", "HD"],
    ["413", "GEMINI MOVIES HD", "2", "HD"],
    ["414", "GEMINI MUSIC HD", "2", "HD"],
    ["415", "GEMINI TV HD", "2", "HD"],
    ["416", "HISTORY TV18 HD", "2", "HD"],
    ["417", "KTV HD", "2", "HD"],
    ["418", "MAZHAVIL MANORAMA HD", "2", "HD"],
    ["419", "MN+ HD", "2", "HD"],
    ["420", "MNX HD", "2", "HD"],
    ["421", "MOVIES NOW HD", "2", "HD"],
    ["422", "MTV BEATS HD", "2", "HD"],
    ["423", "NAT GEO WILD HD", "2", "HD"],
    ["424", "NGC HD", "2", "HD"],
    ["425", "NHK WORLD HD", "2", "HD"],
    ["426", "NICK HD", "2", "HD"],
    ["427", "SANGAMAM HD", "2", "HD"],
    ["428", "SONY BBC EARTH HD", "2", "HD"],
    ["429", "SONY ENTERTAINMENT HD", "2", "HD"],
    ["430", "SONY MAX HD", "2", "HD"],
    ["431", "SONY PIX HD", "2", "HD"],
    ["432", "SONY SAB HD", "2", "HD"],
    ["433", "SONY SIX HD", "2", "HD"],
    ["434", "SONY TEN 1 HD", "2", "HD"],
    ["435", "SONY TEN 2 HD", "2", "HD"],
    ["436", "SONY TEN 3 HD", "2", "HD"],
    ["437", "SONY TEN 4 HD", "2", "HD"],
    ["438", "STAR BHARAT HD", "2", "HD"],
    ["439", "STAR GOLD HD", "2", "HD"],
    ["440", "STAR GOLD SELECT HD", "2", "HD"],
    ["441", "STAR MAA HD", "2", "HD"],
    ["442", "STAR MAA MOVIES HD", "2", "HD"],
    ["443", "STAR MOVIES HD", "2", "HD"],
    ["444", "STAR MOVIES SELECT HD", "2", "HD"],
    ["445", "STAR PLUS HD", "2", "HD"],
    ["446", "STAR SPORTS 1 HD", "2", "HD"],
    ["447", "STAR SPORTS 1 HD HINDI", "2", "HD"],
    ["448", "STAR SPORTS 2 HD", "2", "HD"],
    ["449", "STAR SPORTS SELECT 1 HD", "2", "HD"],
    ["450", "STAR SPORTS SELECT 2 HD", "2", "HD"],
    ["451", "STAR SUVARNA HD", "2", "HD"],
    ["452", "STAR VIJAY HD", "2", "HD"],
    ["453", "STAR WORLD HD", "2", "HD"],
    ["454", "SUN MUSIC HD", "2", "HD"],
    ["455", "SUN TV HD", "2", "HD"],
    ["456", "SURYA TV HD", "2", "HD"],
    ["457", "TEST HD", "2", "HD"],
    ["458", "TESTING 1", "2", "HD"],
    ["459", "TESTING 2", "2", "HD"],
    ["460", "TIMES NOW HD", "2", "HD"],
    ["461", "TIMES NOW NAVBHARATH HD", "2", "HD"],
    ["462", "TLC HD", "2", "HD"],
    ["463", "TRAVEL XP HD", "2", "HD"],
    ["464", "UDAYA TV HD", "2", "HD"],
    ["465", "UTV HD", "2", "HD"],
    ["466", "VH1 HD", "2", "HD"],
    ["467", "ZEE CAFE HD", "2", "HD"],
    ["468", "ZEE CINEMA HD", "2", "HD"],
    ["469", "ZEE CINEMALU HD", "2", "HD"],
    ["470", "ZEE KANNADA HD", "2", "HD"],
    ["471", "ZEE KERALAM HD", "2", "HD"],
    ["472", "ZEE PICCHAR HD", "2", "HD"],
    ["473", "ZEE TAMIL HD", "2", "HD"],
    ["474", "ZEE TELUGU HD", "2", "HD"],
    ["475", "ZEE THIRAI HD", "2", "HD"],
    ["476", "ZEE TV HD", "2", "HD"],
    ["477", "ZEE ZEST HD", "2", "HD"]

          ],
        },
        {
          tableHead: ["S.No", "Channel Name", "Count in SD Terms", "SD / HD"],
          tableRows: [
 ["1", "& FLIX", "1", "SD"],
      ["2", "& PICTURES", "1", "SD"],
      ["3", "& TV", "1", "SD"],
      ["4", "1 YES CHANNEL", "1", "SD"],
      ["5", "10 TV", "1", "SD"],
      ["6", "1st India", "1", "SD"],
      ["7", "24 News", "1", "SD"],
      ["8", "7S MUSIC", "1", "SD"],
      ["9", "9X JALWA", "1", "SD"],
      ["10", "9X JHAKAAS", "1", "SD"],
      ["11", "9XM", "1", "SD"],
      ["12", "AAJ TAK", "1", "SD"],
      ["13", "AAJ TAK TEZ", "1", "SD"],
      ["14", "AAKASH AATH", "1", "SD"],
      ["15", "AASTHA", "1", "SD"],
      ["16", "AASTHA BHAJAN", "1", "SD"],
      ["17", "ABN ANDHRA JHOTI", "1", "SD"],
      ["18", "ABP NEWS", "1", "SD"],
      ["19", "ADITHYA", "1", "SD"],
      ["20", "ALJAZEERA SD", "1", "SD"],
      ["21", "AMRITA", "1", "SD"],
      ["22", "ANGEL TV", "1", "SD"],
      ["23", "ANIMAL PLANET", "1", "SD"],
      ["24", "ANJAN TV", "1", "SD"],
      ["25", "ARADANA", "1", "SD"],
      ["26", "ARIHANT", "1", "SD"],
      ["27", "ASEERVATHAM", "1", "SD"],
      ["28", "ASIANET", "1", "SD"],
      ["29", "ASIANET MOVIES", "1", "SD"],
      ["30", "ASIANET NEWS", "1", "SD"],
      ["31", "ASIANET PLUS", "1", "SD"],
      ["32", "AYUSH TV", "1", "SD"],
      ["33", "B4U MOVIES", "1", "SD"],
      ["34", "B4U MUSIC", "1", "SD"],
      ["35", "BBC WORLD NEWS", "1", "SD"],
      ["36", "Bflix Movies", "1", "SD"],
      ["37", "BHAKTHI", "1", "SD"],
      ["38", "BIG MAGIC", "1", "SD"],
      ["39", "BTV NEWS", "1", "SD"],
      ["40", "CAPTAIN NEWS", "1", "SD"],
      ["41", "CAPTAIN TV", "1", "SD"],
      ["42", "CARE WORLD", "1", "SD"],
      ["43", "CARTOON NETWORK", "1", "SD"],
      ["44", "CGTN", "1", "SD"],
      ["45", "CHANNEL WIN", "1", "SD"],
      ["46", "CHINTU TV", "1", "SD"],
      ["47", "CHITHIRAM", "1", "SD"],
      ["48", "CHUTTI TV", "1", "SD"],
      ["49", "CINEMA TV (NT 8)", "1", "SD"],
      ["50", "CNBC AWAAZ", "1", "SD"],
      ["51", "CNBC TV18", "1", "SD"],
      ["52", "CNN INTERNATIONAL", "1", "SD"],
      ["53", "CNN NEWS18", "1", "SD"],
      ["54", "COLORS", "1", "SD"],
      ["55", "COLORS BANGLA", "1", "SD"],
      ["56", "COLORS CINEPLEX", "1", "SD"],
      ["57", "COLORS GUJRATHI", "1", "SD"],
      ["58", "COLORS INFINITY", "1", "SD"],
      ["59", "COLORS KANNADA", "1", "SD"],
      ["60", "COLORS KANNADA CINEMA", "1", "SD"],
      ["61", "COLORS MARATHI", "1", "SD"],
      ["62", "COLORS ODIA", "1", "SD"],
      ["63", "COLORS RISHTEY", "1", "SD"],
      ["64", "COLORS SUPER", "1", "SD"],
      ["65", "COLORS TAMIL", "1", "SD"],
      ["66", "COMEDY CENTRAL", "1", "SD"],
      ["67", "CONSUMER IFO", "1", "SD"],
      ["68", "CVR HEALTH", "1", "SD"],
      ["69", "DABANGG", "1", "SD"],
      ["70", "DANGAL", "1", "SD"],
      ["71", "DANGAL KANNADA", "1", "SD"],
      ["72", "DARSHAN 24", "1", "SD"],
      ["73", "DD ARUNPRABHA", "1", "SD"],
      ["74", "DD BANGLA", "1", "SD"],
      ["75", "DD BHARATHI", "1", "SD"],
      ["76", "DD BIHAR", "1", "SD"],
      ["77", "DD CHANDANA", "1", "SD"],
      ["78", "DD GIRNAR", "1", "SD"],
      ["79", "DD GYANDHARASHAN 1", "1", "SD"],
      ["80", "DD GYANDHARASHAN 2", "1", "SD"],
      ["81", "DD INDIA", "1", "SD"],
      ["82", "DD KASHIR", "1", "SD"],
      ["83", "DD KISAN", "1", "SD"],
      ["84", "DD LOKSABHA", "1", "SD"],
      ["85", "DD MALAYALAM", "1", "SD"],
      ["86", "DD MP", "1", "SD"],
      ["87", "DD NATIONAL", "1", "SD"],
      ["88", "DD NEWS", "1", "SD"],
      ["89", "DD NORTHEAST", "1", "SD"],
      ["90", "DD ODIA", "1", "SD"],
      ["91", "DD PODHIGAI", "1", "SD"],
      ["92", "DD PUDUCHERRY", "1", "SD"],
      ["93", "DD PUNJABI", "1", "SD"],
      ["94", "DD RAJASTHAN", "1", "SD"],
      ["95", "DD RAJYASABHA", "1", "SD"],
      ["96", "DD SAHYADRI", "1", "SD"],
      ["97", "DD SAPTHAGIRI", "1", "SD"],
      ["98", "DD SPORTS", "1", "SD"],
      ["99", "DD UP", "1", "SD"],
      ["100", "DD URDU", "1", "SD"],
      ["101", "DD YADAGIRI", "1", "SD"],
      ["102", "DHEERAN TV", "1", "SD"],
      ["103", "DIGVIJAY NEWS 24X7", "1", "SD"],
      ["104", "DISCOVERY", "1", "SD"],
      ["105", "DISCOVERY KIDS", "1", "SD"],
      ["106", "DISCOVERY SCIENCE", "1", "SD"],
      ["107", "DISCOVERY TAMIL", "1", "SD"],
      ["108", "DISCOVERY TURBO", "1", "SD"],
      ["109", "DISNEY", "1", "SD"],
      ["110", "DISNEY JUNIOR", "1", "SD"],
      ["111", "DIVYA", "1", "SD"],
      ["112", "DW ASIA", "1", "SD"],
      ["113", "DY 365", "1", "SD"],
      ["114", "E 24", "1", "SD"],
      ["115", "ENTER 10", "1", "SD"],
      ["116", "ET NOW", "1", "SD"],
      ["117", "ETV", "1", "SD"],
      ["118", "ETV ABIRUCHI", "1", "SD"],
      ["119", "ETV AP", "1", "SD"],
      ["120", "ETV CINEMA", "1", "SD"],
      ["121", "ETV LIFE", "1", "SD"],
      ["122", "ETV PLUS", "1", "SD"],
      ["123", "ETV TELANGANA", "1", "SD"],
      ["124", "EUROSPORT", "1", "SD"],
      ["125", "FASHION TV", "1", "SD"],
      ["126", "Fateh TV", "1", "SD"],
      ["127", "FILMY", "1", "SD"],
      ["128", "FAKT MARATHI", "1", "SD"],
      ["129", "FLOWERS TV", "1", "SD"],
      ["130", "FOOD FOOD", "1", "SD"],
      ["131", "FOX LIFE", "1", "SD"],
      ["132", "FRANCE TV", "1", "SD"],
      ["133", "GEMINI COMEDY", "1", "SD"],
      ["134", "GEMINI LIFE", "1", "SD"],
      ["135", "GEMINI MOVIES", "1", "SD"],
      ["136", "GEMINI MUSIC", "1", "SD"],
      ["137", "GEMINI TV", "1", "SD"],
      ["138", "GOD TV", "1", "SD"],
      ["139", "GOODNESS", "1", "SD"],
      ["140", "HISTORY TV18", "1", "SD"],
      ["141", "HM TV", "1", "SD"],
      ["142", "HUNGAMA", "1", "SD"],
      ["143", "I NEWS", "1", "SD"],
      ["144", "IMAYAM TV", "1", "SD"],
      ["145", "INDIA AHEAD", "1", "SD"],
      ["146", "INDIA TODAY", "1", "SD"],
      ["147", "INDIA TV", "1", "SD"],
      ["148", "INVESTIGATION DISCOVERY", "1", "SD"],
      ["149", "IPLUS TV", "1", "SD"],
      ["150", "ISAI ARUVI", "1", "SD"],
      ["151", "J MOVIES", "1", "SD"],
      ["152", "JANAM TV", "1", "SD"],
      ["153", "JANATAA TV", "1", "SD"],
      ["154", "JAYA MAX", "1", "SD"],
      ["155", "JAYA PLUS", "1", "SD"],
      ["156", "JAYA TV", "1", "SD"],
      ["157", "JEEVAN TV", "1", "SD"],
      ["158", "K News India", "1", "SD"],
      ["159", "KAIRALI", "1", "SD"],
      ["160", "KAIRALI NEWS", "1", "SD"],
      ["161", "KAIRALI WE", "1", "SD"],
      ["162", "KALAIGNAR TV", "1", "SD"],
      ["163", "KAPPA TV", "1", "SD"],
      ["164", "KASTHURI NEWS", "1", "SD"],
      ["165", "KASTHURI TV", "1", "SD"],
      ["166", "KAUMUDY", "1", "SD"],
      ["167", "KERALA VISION", "1", "SD"],
      ["168", "KISHORE MANCH", "1", "SD"],
      ["169", "KOCHU TV", "1", "SD"],
      ["170", "KTV", "1", "SD"],
      ["171", "KUSHI TV", "1", "SD"],
      ["172", "LORD BUDDHA TV", "1", "SD"],
      ["173", "LOTUS NEWS", "1", "SD"],
      ["174", "MADHA TV", "1", "SD"],
      ["175", "MADHIMUGAM", "1", "SD"],
      ["176", "Maha Movie", "1", "SD"],
      ["177", "MAHAA NEWS", "1", "SD"],
      ["178", "Mahavira TV", "1", "SD"],
      ["179", "MAIBOLI", "1", "SD"],
      ["180", "MAKKAL TV", "1", "SD"],
      ["181", "MALAI MURASU", "1", "SD"],
      ["182", "MANORAMA NEWS", "1", "SD"],
      ["183", "MANORANJAN TV", "1", "SD"],
      ["184", "MARVEL HQ", "1", "SD"],
      ["185", "MASTII", "1", "SD"],
      ["186", "MATHRUBHUMI NEWS", "1", "SD"],
      ["187", "MAZHAVIL MANORAMA", "1", "SD"],
      ["188", "MEGA 24", "1", "SD"],
      ["189", "MEGA MUSIC", "1", "SD"],
      ["190", "MEGA TV", "1", "SD"],
      ["191", "MIRROR NOW", "1", "SD"],
      ["192", "MNX", "1", "SD"],
      ["193", "MOVIES NOW", "1", "SD"],
      ["194", "MTV", "1", "SD"],
      ["195", "MTV BEATS", "1", "SD"],
      ["196", "MURASU", "1", "SD"],
      ["197", "MUSIC INDIA", "1", "SD"],
      ["198", "N TV", "1", "SD"],
      ["199", "NAAPTOL KANNADA", "1", "SD"],
      ["200", "NAMBIKAI TV", "1", "SD"],
      ["201", "NAT GEO WILD", "1", "SD"],
      ["202", "NDTV 24X7", "1", "SD"],
      ["203", "NDTV GOODTIMES", "1", "SD"],
      ["204", "NDTV INDIA", "1", "SD"],
      ["205", "NDTV PROFIT", "1", "SD"],
      ["206", "NEPAL 1", "1", "SD"],
      ["207", "News 18 KERELA", "1", "SD"],
      ["208", "NEWS J", "1", "SD"],
      ["209", "NEWS18 BANGLA", "1", "SD"],
      ["210", "NEWS18 INDIA", "1", "SD"],
      ["211", "NEWS18 KANNADA", "1", "SD"],
      ["212", "NEWS18 LOKMAT", "1", "SD"],
      ["213", "NEWS18 RAJASTHAN", "1", "SD"],
      ["214", "NEWS18 TAMILNADU", "1", "SD"],
      ["215", "NEWS18 URDU", "1", "SD"],
      ["216", "NEWS7 TAMIL", "1", "SD"],
      ["217", "NGC", "1", "SD"],
      ["218", "NICK", "1", "SD"],
      ["219", "NICK JUNIOR", "1", "SD"],
      ["220", "Odisha TV", "1", "SD"],
      ["221", "OM TV", "1", "SD"],
      ["222", "PANINI", "1", "SD"],
      ["223", "PARAS", "1", "SD"],
      ["224", "PEACE OF MIND", "1", "SD"],
      ["225", "POGO", "1", "SD"],
      ["226", "POLIMER", "1", "SD"],
      ["227", "POLIMER NEWS", "1", "SD"],
      ["228", "POWER TV", "1", "SD"],
      ["229", "PRAJAA TV KANNADA NEWS", "1", "SD"],
      ["230", "PTC NEWS", "1", "SD"],
      ["231", "PTC PUNJABI", "1", "SD"],
      ["232", "PUBLIC MOVIES", "1", "SD"],
      ["233", "PUBLIC MUSIC", "1", "SD"],
      ["234", "PUBLIC TV NEWS", "1", "SD"],
      ["235", "PUTHIYA THALAIMURAI", "1", "SD"],
      ["236", "PUTHUYUGAM", "1", "SD"],
      ["237", "RAJ DIGITAL PLUS", "1", "SD"],
      ["238", "RAJ MUSIC", "1", "SD"],
      ["239", "RAJ MUSIC KANNADA", "1", "SD"],
      ["240", "RAJ MUSIC TELGU", "1", "SD"],
      ["241", "RAJ NEWS", "1", "SD"],
      ["242", "RAJ NEWS KANNADA", "1", "SD"],
      ["243", "RAJ NEWS TELUGU", "1", "SD"],
      ["244", "RAJ PARIWAR", "1", "SD"],
      ["245", "RAJ TV", "1", "SD"],
      ["246", "REPORTER", "1", "SD"],
      ["247", "Republic Bharat", "1", "SD"],
      ["248", "REPUBLIC TV", "1", "SD"],
      ["249", "ROMEDY NOW", "1", "SD"],
      ["250", "RUPASI BANGLA", "1", "SD"],
      ["251", "RUSSIA TODAY", "1", "SD"],
      ["252", "SADHNA", "1", "SD"],
      ["253", "SAFARI", "1", "SD"],
      ["254", "SAHANA", "1", "SD"],
      ["255", "SAHARA ONE", "1", "SD"],
      ["256", "SAI TV", "1", "SD"],
      ["257", "SAKSHI TV", "1", "SD"],
      ["258", "SALVATION", "1", "SD"],
      ["259", "SANGAMAM", "1", "SD"],
      ["260", "SANGEET BANGLA", "1", "SD"],
      ["261", "SANGEET BHOJIPURI", "1", "SD"],
      ["262", "SANSKAR", "1", "SD"],
      ["263", "SATHYAM", "1", "SD"],
      ["264", "SATSANG", "1", "SD"],
      ["265", "SEITHIGAL", "1", "SD"],
      ["266", "SHALOM", "1", "SD"],
      ["267", "SHARDA", "1", "SD"],
      ["268", "ShowBox", "1", "SD"],
      ["269", "SHUBHSANDESH", "1", "SD"],
      ["270", "SIRIPOLI", "1", "SD"],
      ["271", "SONIC", "1", "SD"],
      ["272", "SONY AATH", "1", "SD"],
      ["273", "SONY BBC EARTH", "1", "SD"],
      ["274", "SONY ENTERTAINMENT", "1", "SD"],
      ["275", "SONY MARATHI", "1", "SD"],
      ["276", "SONY MAX", "1", "SD"],
      ["277", "SONY MAX 2", "1", "SD"],
      ["278", "SONY PAL", "1", "SD"],
      ["279", "SONY PIX", "1", "SD"],
      ["280", "SONY SAB", "1", "SD"],
      ["281", "SONY SIX", "1", "SD"],
      ["282", "SONY TEN 1", "1", "SD"],
      ["283", "SONY TEN 2", "1", "SD"],
      ["284", "SONY TEN 3", "1", "SD"],
      ["285", "SONY WAH", "1", "SD"],
      ["286", "SONY YAY", "1", "SD"],
      ["287", "SRI SANKARA", "1", "SD"],
      ["288", "STAR BHARAT", "1", "SD"],
      ["289", "STAR GOLD", "1", "SD"],
      ["290", "STAR GOLD 2", "1", "SD"],
      ["291", "STAR GOLD SELECT", "1", "SD"],
      ["292", "STAR JALSHA", "1", "SD"],
      ["293", "STAR JALSHA MOVIES", "1", "SD"],
      ["294", "STAR MAA GOLD", "1", "SD"],
      ["295", "STAR MAA MOVIES", "1", "SD"],
      ["296", "STAR MAA MUSIC", "1", "SD"],
      ["297", "STAR MAA TV", "1", "SD"],
      ["298", "STAR MOVIES", "1", "SD"],
      ["299", "STAR PARVAH", "1", "SD"],
      ["300", "STAR PLUS", "1", "SD"],
      ["301", "STAR SPORTS 1", "1", "SD"],
      ["302", "STAR SPORTS 1 HINDI", "1", "SD"],
      ["303", "STAR SPORTS 1 KANNADA", "1", "SD"],
      ["304", "STAR SPORTS 1 TAMIL", "1", "SD"],
      ["305", "STAR SPORTS 1 TELUGU", "1", "SD"],
      ["306", "STAR SPORTS 2", "1", "SD"],
      ["307", "STAR SPORTS 3", "1", "SD"],
      ["308", "STAR SPORTS FIRST", "1", "SD"],
      ["309", "STAR SPORTS SELECT 1", "1", "SD"],
      ["310", "STAR SPORTS SELECT 2", "1", "SD"],
      ["311", "STAR SUVARNA", "1", "SD"],
      ["312", "STAR SUVARNA NEWS", "1", "SD"],
      ["313", "STAR SUVARNA PLUS", "1", "SD"],
      ["314", "STAR UTSAV", "1", "SD"],
      ["315", "STAR UTSAV MOVIES", "1", "SD"],
      ["316", "STAR VIJAY", "1", "SD"],
      ["317", "STAR VIJAY SUPER", "1", "SD"],
      ["318", "STAR WORLD", "1", "SD"],
      ["319", "SUBHAVAARTHA", "1", "SD"],
      ["320", "SUN BANGLA", "1", "SD"],
      ["321", "SUN LIFE", "1", "SD"],
      ["322", "SUN MUSIC", "1", "SD"],
      ["323", "SUN NEWS", "1", "SD"],
      ["324", "SUN TV", "1", "SD"],
      ["325", "SURYA", "1", "SD"],
      ["326", "SURYA COMEDY", "1", "SD"],
      ["327", "SURYA MOVIES", "1", "SD"],
      ["328", "SURYA MUSIC", "1", "SD"],
      ["329", "SVBC TAMIL", "1", "SD"],
      ["330", "SVBC TELUGU", "1", "SD"],
      ["331", "TAMILAN TV", "1", "SD"],
      ["332", "TEHZEEB", "1", "SD"],
      ["333", "THANTHI TV", "1", "SD"],
      ["334", "TIMES NOW", "1", "SD"],
      ["335", "TLC", "1", "SD"],
      ["336", "TRAVEL XP", "1", "SD"],
      ["337", "TRAVEL XP TAMIL", "1", "SD"],
      ["338", "TV5 KANNADA", "1", "SD"],
      ["339", "TV5 MONDE", "1", "SD"],
      ["340", "TV5 NEWS", "1", "SD"],
      ["341", "TV9 GUJARATI", "1", "SD"],
      ["342", "TV9 KANNADA", "1", "SD"],
      ["343", "TV9 MARATHI", "1", "SD"],
      ["344", "TV9 TELUGU", "1", "SD"],
      ["345", "UDAYA COMEDY", "1", "SD"],
      ["346", "UDAYA MOVIES", "1", "SD"],
      ["347", "UDAYA MUSIC", "1", "SD"],
      ["348", "UTV ACTION", "1", "SD"],
      ["349", "UTV BINDASS", "1", "SD"],
      ["350", "UTV MOVIES", "1", "SD"],
      ["351", "VANITHA TV", "1", "SD"],
      ["352", "VASANTH TV", "1", "SD"],
      ["353", "VELICHAM TV", "1", "SD"],
      ["354", "VENDHAR TV", "1", "SD"],
      ["355", "VH1", "1", "SD"],
      ["356", "WIN TV", "1", "SD"],
      ["357", "WION", "1", "SD"],
      ["358", "WOW CINEMA", "1", "SD"],
      ["359", "ZEE 24 GHANTA", "1", "SD"],
      ["360", "ZEE 24 TAAS", "1", "SD"],
      ["361", "ZEE ACTION", "1", "SD"],
      ["362", "ZEE ANMOL", "1", "SD"],
      ["363", "ZEE BANGLA", "1", "SD"],
      ["364", "ZEE BANGLA CINEMA", "1", "SD"],
      ["365", "ZEE BIHAR JHARKHAND", "1", "SD"],
      ["366", "ZEE BOLLYWOOD", "1", "SD"],
      ["367", "ZEE BUSINESS", "1", "SD"],
      ["368", "ZEE CAFE", "1", "SD"],
      ["369", "ZEE CINEMA", "1", "SD"],
      ["370", "ZEE CINEMALU", "1", "SD"],
      ["371", "ZEE CLASSIC", "1", "SD"],
      ["372", "ZEE HINDUSTAN", "1", "SD"],
      ["373", "ZEE KALINGA", "1", "SD"],
      ["374", "ZEE KANNADA", "1", "SD"],
      ["375", "ZEE KERALAM", "1", "SD"],
      ["376", "ZEE MARATHI", "1", "SD"],
      ["377", "ZEE NEWS", "1", "SD"],
      ["378", "ZEE PICHHAR", "1", "SD"],
      ["379", "ZEE PUNJAB / HARIYANA", "1", "SD"],
      ["380", "ZEE SALAM", "1", "SD"],
      ["381", "ZEE TALKIES", "1", "SD"],
      ["382", "ZEE TAMIL", "1", "SD"],
      ["383", "ZEE TELUGU", "1", "SD"],
      ["384", "ZEE TV", "1", "SD"],
      ["385", "ZEE YUVA", "1", "SD"],
      ["386", "ZING", "1", "SD"],
      ["387", "ZOOM", "1", "SD"],
      ["388", "& FLIX HD", "2", "HD"],
      ["389", "& PICTURES HD", "2", "HD"],
      ["390", "& PRIVE HD", "2", "HD"],
      ["391", "AAJ TAK HD", "2", "HD"],
      ["392", "ANIMAL PLANET HD", "2", "HD"],
      ["393", "ASIANET HD", "2", "HD"],
      ["394", "BABY TV HD", "2", "HD"],
      ["395", "CN HD+", "2", "HD"],
      ["396", "CNBC PRIME HD", "2", "HD"],
      ["397", "COLORS CINEPLEX HD", "2", "HD"],
      ["398", "COLORS HD", "2", "HD"],
      ["399", "COLORS INFINITY HD", "2", "HD"],
      ["400", "COLORS KANNADA HD", "2", "HD"],
      ["401", "COLORS TAMIL HD", "2", "HD"],
      ["402", "COMEDY CENTRAL HD", "2", "HD"],
      ["403", "DD NATIONAL HD", "2", "HD"],
      ["404", "DISCOVERY HD WORLD", "2", "HD"],
      ["405", "DISNEY HD", "2", "HD"],
      ["406", "ETV HD", "2", "HD"],
      ["407", "EUROSPORT HD", "2", "HD"],
      ["408", "FASHION TV HD", "2", "HD"],
      ["409", "FOX LIFE HD", "2", "HD"],
      ["410", "GEMINI MOVIES HD", "2", "HD"],
      ["411", "GEMINI MUSIC HD", "2", "HD"],
      ["412", "GEMINI TV HD", "2", "HD"],
      ["413", "HISTORY TV18 HD", "2", "HD"],
      ["414", "KTV HD", "2", "HD"],
      ["415", "MAZHAVIL MANORAMA HD", "2", "HD"],
      ["416", "MN+ HD", "2", "HD"],
      ["417", "MNX HD", "2", "HD"],
      ["418", "MOVIES NOW HD", "2", "HD"],
      ["419", "MTV BEATS HD", "2", "HD"],
      ["420", "NAT GEO WILD HD", "2", "HD"],
      ["421", "NGC HD", "2", "HD"],
      ["422", "NHK WORLD HD", "2", "HD"],
      ["423", "NICK HD", "2", "HD"],
      ["424", "ROMEDY NOW HD", "2", "HD"],
      ["425", "SANGAMAM HD", "2", "HD"],
      ["426", "SONY BBC EARTH HD", "2", "HD"],
      ["427", "SONY ENTERTAINMENT HD", "2", "HD"],
      ["428", "SONY MAX HD", "2", "HD"],
      ["429", "SONY PIX HD", "2", "HD"],
      ["430", "SONY SAB HD", "2", "HD"],
      ["431", "SONY SIX HD", "2", "HD"],
      ["432", "SONY TEN 1 HD", "2", "HD"],
      ["433", "SONY TEN 2 HD", "2", "HD"],
      ["434", "SONY TEN 3 HD", "2", "HD"],
      ["435", "STAR BHARAT HD", "2", "HD"],
      ["436", "STAR GOLD HD", "2", "HD"],
      ["437", "STAR GOLD SELECT HD", "2", "HD"],
      ["438", "STAR MAA HD", "2", "HD"],
      ["439", "STAR MAA MOVIES HD", "2", "HD"],
      ["440", "STAR MOVIES HD", "2", "HD"],
      ["441", "STAR MOVIES SELECT HD", "2", "HD"],
      ["442", "STAR PLUS HD", "2", "HD"],
      ["443", "STAR SPORTS 1 HD", "2", "HD"],
      ["444", "STAR SPORTS 1 HD HINDI", "2", "HD"],
      ["445", "STAR SPORTS 2 HD", "2", "HD"],
      ["446", "STAR SPORTS SELECT 1 HD", "2", "HD"],
      ["447", "STAR SPORTS SELECT 2 HD", "2", "HD"],
      ["448", "STAR SUVARNA HD", "2", "HD"],
      ["449", "STAR VIJAY HD", "2", "HD"],
      ["450", "STAR WORLD HD", "2", "HD"],
      ["451", "STAR WORLD PREMIER HD", "2", "HD"],
      ["452", "SUN MUSIC HD", "2", "HD"],
      ["453", "SUN TV HD", "2", "HD"],
      ["454", "SURYA TV HD", "2", "HD"],
      ["455", "TIMES NOW HD", "2", "HD"],
      ["456", "TLC HD", "2", "HD"],
      ["457", "TRAVEL XP HD", "2", "HD"],
      ["458", "UDAYA TV HD", "2", "HD"],
      ["459", "UTV HD", "2", "HD"],
      ["460", "VH1 HD", "2", "HD"],
      ["461", "ZEE CAFE HD", "2", "HD"],
      ["462", "ZEE CINEMA HD", "2", "HD"],
      ["463", "ZEE CINEMALU HD", "2", "HD"],
      ["464", "ZEE KANNADA HD", "2", "HD"],
      ["465", "ZEE KERALAM HD", "2", "HD"],
      ["466", "ZEE TAMIL HD", "2", "HD"],
      ["467", "ZEE TELUGU HD", "2", "HD"],
      ["468", "ZEE TV HD", "2", "HD"],
      ["469", "BHOJPURI CINEMA", "1", "SD"],
      ["470", "OSCOR MOVIES BHOJPURI", "1", "SD"],
      ["471", "STAR VIJAY MUISC", "1", "SD"],
      ["472", "UDAYA TV", "1", "SD"],
      ["473", "ZEE THIRAI", "1", "SD"],
      ["474", "ZEE ZEST", "1", "SD"],
      ["475", "ZEE ZEST HD", "2", "HD"],
      ["476", "LOCAL 1 ROK", "1", "SD"],
      ["477", "LOCAL 2 ROK", "1", "SD"],
      ["478", "LOCAL 3 ROK", "1", "SD"],
      ["479", "LOCAL 4 ROK", "1", "SD"],
      ["480", "LOCAL 5 ROK", "1", "SD"],
      ["481", "LOCAL 6 ROK", "1", "SD"],
      ["482", "LOCAL 7 ROK", "1", "SD"],
      ["483", "LOCAL 8 ROK", "1", "SD"],
      ["484", "LOCAL 9 ROK", "1", "SD"],
      ["485", "LOCAL 10 ROK", "1", "SD"],
      ["486", "LOCAL 11 ROK", "1", "SD"],
      ["487", "LOCAL 12 ROK", "1", "SD"],
      ["488", "LOCAL 13 ROK", "1", "SD"],
      ["489", "LOCAL 14 ROK", "1", "SD"],
      ["490", "LOCAL 15 ROK", "1", "SD"],
      ["491", "LOCAL 16 ROK", "1", "SD"]

          ],
        },
      ],
    },


    "Regulation 4 (4) (d)": {
      title: "Pursuant to Regulation 4 (4) (d)",
      table: null,
    },

    "Regulation 4 (4) (e)": {
      title: "Pursuant to Regulation 4 (4) (e) — Spare Channel Capacity Available",
      tableHead: ["Distribution Network Location", "Spare Channel Capacity (SD Terms)"],
      tableRows: [
        ["Tamil Nadu", "NIL"],
        ["Pondicherry", "NIL"],
        ["Andhra Pradesh", "NIL"],
        ["Karnataka", "NIL"],
      ],
    },

    "Regulation 4 (4) (f)": {
      title: "Pursuant to Regulation 4 (4) (f)",
      table: null,
    },
  };

  const regs = Object.keys(content);


  return (
    <div>
      <Navbar/>
     <div className="bg-gray-50 min-h-screen">
      <div className="max-w-7xl mx-auto p-6">
        <h1 className="text-4xl font-bold text-[#1a89e5] mb-8">Declaration</h1>

        <div className="flex flex-col md:flex-row gap-6">
          {/* LEFT SIDE CARDS */}
          <div className="w-full md:w-1/3 space-y-3">
            {regs.map((reg, i) => (
            <div
              key={i}
              onClick={() => setSelectedReg(reg)}
              className={`cursor-pointer p-4 rounded-lg font-semibold  transition-all duration-300
                ${
                  selectedReg === reg
                    ? "bg-[#1a89e5] text-white scale-105 py-7 px-7 md:translate-x-2 z-index-68"
                    : "shadow-md bg-white text-gray-800 hover:shadow-lg"
                }`}
            >
              {reg}
            </div>

            ))}
          </div>

          {/* RIGHT SIDE CONTENT */}<div
  className={`w-full md:w-2/3 p-6 rounded-xl shadow-lg border border-gray-200
    ${selectedReg ? "bg-[#1a89e5]" : "bg-[#f3ede1]"}
  `}
>            {selectedReg ? (
              <>
                <h2 className="text-2xl font-bold mb-4 text-white">
                  {content[selectedReg].title}
                </h2>

                {content[selectedReg].tables ? (
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    {content[selectedReg].tables.map((tableData, tableIndex) => (
                      <div key={tableIndex} className="overflow-x-auto">
                        <table className="min-w-full border border-gray-300 rounded-lg overflow-hidden">
                          <thead className="bg-blue-100">
                            <tr>
                              {tableData.tableHead.map((h, i) => (
                                <th
                                  key={i}
                                  className="p-3 text-left text-gray-700 font-medium border-b"
                                >
                                  {h}
                                </th>
                              ))}
                            </tr>
                          </thead>

                          <tbody>
                            {tableData.tableRows.map((row, rIndex) => (
                              <tr
                                key={rIndex}
                                className="hover:bg-gray-50 text-gray-700 transition-colors"
                              >
                                {row.map((col, cIndex) => (
                                  <td
                                    key={cIndex}
                                    className="p-3 border-b text-white"
                                  >
                                    {col}
                                  </td>
                                ))}
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    ))}
                  </div>
                ) : content[selectedReg].tableHead && content[selectedReg].tableRows ? (
                  <div className="overflow-x-auto">
                    <table className="min-w-full border border-gray-300 rounded-lg overflow-hidden">
                      <thead className="bg-blue-100">
                        <tr>
                          {content[selectedReg].tableHead.map((h, i) => (
                            <th
                              key={i}
                              className="p-3 text-left text-gray-700 font-medium border-b"
                            >
                              {h}
                            </th>
                          ))}
                        </tr>
                      </thead>

                      <tbody>
                        {content[selectedReg].tableRows.map((row, rIndex) => (
                          <tr
                            key={rIndex}
                            className="hover:bg-gray-50 transition-colors"
                          >
                            {row.map((col, cIndex) => (
                              <td
                                key={cIndex}
                                className="p-3 border-b text-white"
                              >
                                {col}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                ) : (
                  <p className="text-white mt-4">
                    No table available for this regulation.
                  </p>
                )}
              </>
            ) : (
                <img src="/assets/click.png" className="h-[50vh] mx-auto"/>
            )}
          </div>
        </div>
      </div>
    </div>
    <ContactSection/>
    </div>
  );
};